import { describe, expect, test } from "bun:test";

import { generatedFileGuard } from "../../src/index.ts";
import { errorCode, harness } from "../helpers.ts";
import { change, decided, guardContext, verdict } from "./helpers.ts";

function check(path: string, before: string | null, guard = generatedFileGuard()) {
  return verdict(guard.check(change({ path, before, after: "x" }), guardContext()));
}

describe("generatedFileGuard", () => {
  test.each(["/dist/app.min.js", "/src/api.generated.ts", "/py/msg_pb2.py", "/go/msg.pb.go"])(
    "refuses an update to %s",
    (path) => {
      expect(check(path, "a\n")).toBe("generated-file");
    },
  );

  test.each([
    "// @generated by protoc\n",
    "// Code generated by mockgen. DO NOT EDIT.\n",
    "# This file is Auto-Generated.\n",
  ])("refuses an update to a file whose first lines hold a marker: %s", (head) => {
    expect(check("/src/a.ts", `${head}export const a = 1;\n`)).toBe("generated-file");
  });

  test("near miss: a marker after the first 1 024 characters", () => {
    const before = `${"// padding\n".repeat(100)}// DO NOT EDIT\n`;
    expect(before.indexOf("DO NOT EDIT")).toBeGreaterThan(1_024);
    expect(check("/src/a.ts", before)).toBe("allow");
  });

  test("near miss: names that only look similar, and creates", () => {
    expect(check("/src/admin.js", "a\n")).toBe("allow");
    expect(check("/src/generated.ts", "a\n")).toBe("allow");
    expect(check("/dist/app.min.js", null)).toBe("allow");
  });

  test("the message names the reason", () => {
    const byName = generatedFileGuard().check(
      change({ path: "/dist/app.min.js", before: "a", after: "b" }),
      guardContext(),
    );
    const byMarker = generatedFileGuard().check(
      change({ path: "/a.go", before: "// Code generated. DO NOT EDIT.\n", after: "b" }),
      guardContext(),
    );
    expect(byName).toEqual({
      allow: false,
      note: {
        code: "generated-file",
        severity: "warning",
        message:
          "/dist/app.min.js looks generated: its name, app.min.js, is a generated-file name. Change its source or generator instead, then regenerate it.",
        data: { reason: "its name, app.min.js, is a generated-file name" },
      },
    });
    expect(message(byMarker)).toBe(
      '/a.go looks generated: its first lines hold "DO NOT EDIT". Change its source or generator instead, then regenerate it.',
    );
  });

  test("host markers and names replace the defaults", () => {
    const guard = generatedFileGuard({ markers: [/^# built$/mu], names: [/\.out$/u] });
    expect(check("/a.txt", "# built\n", guard)).toBe("generated-file");
    expect(check("/a.out", "a\n", guard)).toBe("generated-file");
    expect(check("/a.min.js", "// DO NOT EDIT\n", guard)).toBe("allow");
    expect(() => generatedFileGuard({ markers: "x" as never })).toThrow(TypeError);
  });

  test("opt-in: off by default, on when listed", async () => {
    const files = { "/app.min.js": "a();\n" };
    const off = harness({ files });
    await off.read({ path: "/app.min.js" });
    expect((await off.write({ path: "/app.min.js", content: "b();\n" })).status).toBe("ok");
    const on = harness({ files, deps: { guards: [generatedFileGuard()] } });
    await on.read({ path: "/app.min.js" });
    expect(errorCode(await on.write({ path: "/app.min.js", content: "b();\n" }))).toBe(
      "GUARD_REFUSED",
    );
  });
});

function message(decision: Parameters<typeof decided>[0]): string | null {
  const sync = decided(decision);
  return sync.allow ? null : (sync.note?.message ?? null);
}
